---
name: Publish to PyPI

on:
  push:
    tags: ["*"]
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test-reusable.yml
    with:
      package_name: dvla_vehicle_enquiry_service
      tests_path: tests
    secrets: inherit

  publish:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Setup python and restore poetry
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
          cache: "poetry"

      - name: Build package
        run: poetry build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
