---
name: Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test-reusable.yml
    with:
      package_name: dvla_vehicle_enquiry_service
      tests_path: tests
